### ISSUE TITLE
No explicit dependencies versions

### ISSUE THREAD

**Issue by rafidini** [wxllow/applemusicrp#17]
**Problem**
You might have heard of the issues where developers built software that once shipped to the customers, could not run the software on their side. And the only excuse from devs is _"But it works on my machine"_, well here maybe we may get the same issue.

I took a look at your `setup.py` file where you define the metadata for your Python package and I saw that the dependencies are here but not their versions.

I created this issue because in the future you might get (big or small) changes on those dependencies and it might affect your project.

**Solution**
Currently you have this :
```python
install_dependencies = ['pypresence', 'pystray', 'dialite', 'coverpy', 'appdirs', 'toml']
```
You might go for something like this : 
```python
install_dependencies = [
    'pypresence==x.y.z', 
    'pystray>=x.y.z',
    'dialite==x.y.z',
    'coverpy<=x.y.z',
    'appdirs==x.y.z',
    'toml>=x.y.z'
]
```
It is up to your needs.

**Alternative solution**
Download the packages under your project folders, though I do not recommend doing that as it might make your project heavier.

**Additional context**
- Where versions have to be defined : [applemusicrp/setup.py](https://github.com/wxllow/applemusicrp/blob/79a4a1d4ea579f607d04c5f1d9211d4a7f5ec91a/src/applemusicrp/setup.py#L12) (lines 12-13)
- If you need to check your current dependencies on Python use `python -m pip freeze`, it will display your dependencies and their versions!

Hope it is relevant, you can give me feedback on that issue too!

Good luck 🔨

**Comment by wxllow** [comment]
Hey tysm for this, but I tried to, and it didn't work because py2app doesn't support explicit versions ☹️

**Comment by rafidini** [comment]
I will try to check it out during the week on my side.

**Comment by wxllow** [comment]
I now am using [poetry](https://raw.githubusercontent.com/wxllow/applemusicrp/3.2.0b1/pyproject.toml) which has explicit versions for dependencies, so this should prevent this from occurring
