### ISSUE TITLE
Will not open on macOS 10.15

### ISSUE THREAD

**Issue by Quants0** [wxllow/applemusicrp#20]
v3.1.0 will not open at all on macOS 10.15. Every time I try I get a launch error and only option is to terminate. v3.0.0 works fine but I'd like to upgrade.

**Comment by wxllow** [comment]
Hey, I'm sorry about that! Could you please try running it from terminal like so:

 ```
cd /Applications/applemusicrp.app/Contents/macOS
./applemusicrp
``` 

and tell me if it outputs anything

**Comment by Quants0** [comment]
I've tried that, it didn't do anything different.

**Comment by wxllow** [comment]
> I've tried that, it didn't do anything different.

It might not change anything but could u please try the new beta I released today?

<https://github.com/wxllow/applemusicrp/releases/tag/3.2.0b2>

**Comment by wxllow** [comment]
Please see https://github.com/wxllow/applemusicrp/releases/tag/3.2.0 :) Should fix it but lmk if it doesn't
