### ISSUE TITLE
'Sus Music'

### ISSUE THREAD

**Issue by mushrowan** [wxllow/applemusicrp#25]
why
<img width="170" alt="image" src="https://user-images.githubusercontent.com/69822445/177897293-639bd92d-ff70-4d13-bfd6-c5bb9c7f44ca.png">

**Comment by wxllow** [comment]
Did that as a joke and forgot to fix it LOL but its fixed now

**Comment by wxllow** [comment]
Also, are you listening to the 2007 metal album "Silent Waters" by the Finnish heavy metal band founded by Jan Rechberger, Tomi Koivusaari, and Esa Holopainen in 1990? Oh my goodness, I cannot believe the levels of basedness you have reached.

![sus](https://cdn.akamai.steamstatic.com/steam/apps/945360/capsule_616x353.jpg)

**Comment by mushrowan** [comment]
absolutely.

**Comment by crystall1nedev** [comment]
based

**Comment by wxllow** [comment]
> based

fr

**Comment by wxllow** [comment]
this thread is what github issues were made for

**Comment by crystall1nedev** [comment]
exactly
