### ISSUE TITLE
won't work

### ISSUE THREAD

**Issue by dcoolx** [wxllow/applemusicrp#27]
I downloaded the newest version, but when I launched the app, it wouldn't work. I tried running it as administrator, but that also didn't work. So I downloaded an older version, but this time, when I launched it as administrator it said "An unexpected error has occurred while trying to update your Discord status!"

**Comment by wxllow** [comment]
> I downloaded the newest version, but when I launched the app, it wouldn't work. I tried running it as administrator, but that also didn't work. So I downloaded an older version, but this time, when I launched it as administrator it said "An unexpected error has occurred while trying to update your Discord status!"

Do you have Discord open when running it?

**Comment by dcoolx** [comment]
yes, discord's been open when I tried to use both versions

**Comment by dcoolx** [comment]
> > I downloaded the newest version, but when I launched the app, it wouldn't work. I tried running it as administrator, but that also didn't work. So I downloaded an older version, but this time, when I launched it as administrator it said "An unexpected error has occurred while trying to update your Discord status!"
> 
> Do you have Discord open when running it?

yes, discord's been open both times I tried to use the programs

**Comment by Real0ver** [comment]
Same, wouldn't work for me too, using both iTunes Win32 and UWP.

**Comment by dcoolx** [comment]
> Same, wouldn't work for me too, using both iTunes Win32 and UWP.

did you eventually find out a solution or nah?

**Comment by wxllow** [comment]
So is this issue with Windows specifically? I am not home right now, so I do not have access to my Windows machine or VM, but I will look into this next week.

**Comment by youlovecult** [comment]
yeah it literally jus wont work but the old version works fine

**Comment by wxllow** [comment]
Please try this new build https://github.com/wxllow/applemusicrp/releases/tag/3.2.1 :)
