### ISSUE TITLE
Wondering why changing Pause and Play Icons wont affect application

### ISSUE THREAD

**Issue by Natron4** [wxllow/applemusicrp#28]
This first image is what I want the icons to be, and the second is my change not affecting anything...

![image](https://user-images.githubusercontent.com/114454838/192725800-5386c678-556b-43b5-9af7-ca670db0654e.png)
![image](https://user-images.githubusercontent.com/114454838/192725976-72c45552-c322-45c3-8978-b456bbfbb311.png)

**Comment by wxllow** [comment]
Those should be in a diff folder and not included in the executable, oops... but if you want to change the play/pause icons, it is done on Discord's side. You have to create your own Discord application (<https://discord.com/developers/applications>) and then upload the icons in the `Rich Presence → Art Assets` section, naming them `play` and `pause` respectively.

Then, get the client ID from your Discord application and change it in `config.toml` like shown here: <https://github.com/wxllow/applemusicrp/wiki/Configuration#client-id>

**Comment by Natron4** [comment]
Oh awesome, thank you.  Would this only appear on my end?

**Comment by wxllow** [comment]
No, it will appear for anyone viewing your status

**Comment by Natron4** [comment]
Okay thank you.  When doing the application, am I recreating your whole Rich Presence?  Or am I just implementing the play and pause button?

**Comment by Natron4** [comment]
Also does this break their ToS lol?

**Comment by Natron4** [comment]
Unfortunately I don't think this is possible unless done on your end

**Comment by Natron4** [comment]
I might just be an idiot... but it isn't seeming to work.  What am I doing wrong exactly?  Thank you for your patience.

![image](https://user-images.githubusercontent.com/114454838/195228161-893c9f9a-7e0d-42e3-a244-3273131e179d.png)
![image](https://user-images.githubusercontent.com/114454838/195228183-3de3f5c4-d9b9-45cf-9fa8-8555a29ada7d.png)

**Comment by sbgu** [comment]
hmm remove the quotations from the client id maybe
________________________________

**Comment by Natron4** [comment]
I just tried that and yes.  Do you think it's worth a shot to uninstall the App, delete the folders, and restart from square one?

**Comment by sbgu** [comment]
Hmm, first make sure you’re editing the right config file. The file should be named config.toml and be located at C:\Users\<Username>\AppData\Local\wxllow\AppleMusicRP
________________________________

**Comment by Natron4** [comment]
Yes that was what I was editing sadly.  I had multiple versions of the program downloaded so I'm hoping a wipe will do the job.  Which should I download just so I get it right this time?
![image](https://user-images.githubusercontent.com/114454838/195233811-d384f0e6-adcd-421f-9597-9c58e9a2a573.png)

**Comment by sbgu** [comment]
Download the zip file from the latest release 12 days ago
________________________________

**Comment by Natron4** [comment]
Alrighty I just did that.  Now what?

**Comment by sbgu** [comment]
Extract the zip file and run the AppleMusicRP exe file
________________________________

**Comment by Natron4** [comment]
Alright just did that

**Comment by Natron4** [comment]
![image](https://user-images.githubusercontent.com/114454838/195236481-42fb8430-b4d6-40e7-a3d8-431901087b5a.png)

**Comment by Natron4** [comment]
Now should I close the app (also what is the correct way to close it), and paste my rich presence in?

**Comment by sbgu** [comment]
Yes. Right click on the app in the tray and click quit
________________________________

**Comment by Natron4** [comment]
Okay.  If this does not work can we take a look at my Rich Presence?

**Comment by Natron4** [comment]
Luckily for you we wont have to do that :)

It's just the way I wanted it to be

Thank you so much for your patience and guidance!
![image](https://user-images.githubusercontent.com/114454838/195248826-25854220-46b0-4f2a-98c5-68ca64bf295f.png)

**Comment by sbgu** [comment]
I’ve been busy with school and life and was sleeping when u sent that so
I’m sorry for not responding until now. Glad it works tho!
