### ISSUE TITLE
allow changing fallback image

### ISSUE THREAD

**Issue by youlovecult** [wxllow/applemusicrp#31]
Since i know local files you cant really find the cover can we just have it not show any cover like spotify does? instead of the apple music symbol

**Comment by wxllow** [comment]
If you want to change the fallback image, you will need to use your own Discord Application as that's done on Discord's side.

 You have to create your own Discord application (<https://discord.com/developers/applications>) and then upload your fallback image of choice in the `Rich Presence → Art Assets` section, naming it `logo`.

Then, get the client ID from your Discord application and change it in `config.toml` like shown here: <https://github.com/wxllow/applemusicrp/wiki/Configuration#client-id>

You will also want to upload the play/pause icons, if you so desire to have those. (You can find them and download them here: https://github.com/wxllow/applemusicrp/tree/master/logos, name them `play` and `pause` respectively)

**Comment by wxllow** [comment]
In a next update, I can add a feature to use a custom url for the fallback image

**Comment by youlovecult** [comment]
When that happens I’ll be sure to get back to you
