### ISSUE TITLE
Crash on potential single letter song titles

### ISSUE THREAD

**Issue by JadenAnjara** [wxllow/applemusicrp#37]
Had the app crash specifically on the four songs "P", "I", "N" and "K" of Jaden's ERYS album (explicit versions if it matters). All the other 13 songs in the same album worked perfectly
The crash also seem to occur on the songs "B", "L", "U" and "E". I don't have any other single character songs to try it on at the moment in case this would be the issue

**Comment by wxllow** [comment]
Discord requires a minimum of 2 characters for the details field. Did you change your config file to be just the song name?

**Comment by JadenAnjara** [comment]
Oh, so that is why, thank you !

**Comment by wxllow** [comment]
i tested it and it seems to work!

**Comment by JadenAnjara** [comment]
Thank you !
