### ISSUE TITLE
Doesn't work on macOS 12.3

### ISSUE THREAD

**Issue by PriZmRL** [wxllow/applemusicrp#5]
It sadly doesn't work on macOS. Is there any way i can grab logs to help you out?

**Comment by wxllow** [comment]
Are u sure? I'm on 12.3, and it works for me... I have a few questions so I can help:
1. Are you using an Apple Silicon (M1) or Intel CPU (You can check in Apple Icon > About This Mac > and then the "Chip" section)
2. Do you have Discord opened when you launch the app?
3. What error do you get when you try running the app?

**Comment by wxllow** [comment]
> I'm running M1 Macbook Air, alongside with the latest discord client (apple silicon native one)
> 
> I'm not getting any error messages at all, the app is sitting in menubar, both music app and discord are running. When i play music, i open up discord and i'm not seeing any changes in status

do you have music playing? if not it wont show up anything...

**Comment by PriZmRL** [comment]
Yes, i do have music playing

I've tried using it while music is playing already, and starting music after launching it

both didn't work

**Comment by wxllow** [comment]
> Yes, i do have music playing
> 
> I've tried using it while music is playing already, and starting music after launching it
> 
> both didn't work

`/path/to/applemusicrp.app/Contents/MacOS/applemusicrp` run this in terminal (but replace the beginning with the path to the app ofc) and if it says anything send to me pls

**Comment by wxllow** [comment]
also make sure u dont have ur activity status disabled (discord settings > activity status > "Display current activity as status message" should be enabled) 

and kinda obvious but if you haven't try restarting discord and restarting the music app

**Comment by wxllow** [comment]
> here's the terminal output:
> 
> Exception in thread Thread-1: Traceback (most recent call last): File "threading.pyc", line 973, in _bootstrap_inner File "threading.pyc", line 910, in run File "/Applications/applemusicrp.app/Contents/Resources/applemusicrp.py", line 100, in rp_updater (time.time()-int(float(info[4]))) if info[0] == "PLAYING" else None)) ValueError: could not convert string to float: '0,0'

oh that's weird... does this quick fix i made work? <https://github.com/wxllow/applemusicrp/releases/tag/2.1.1>

**Comment by wxllow** [comment]
didn't mean to close, also are you playing Apple Music files or local files? Not that it would matter, but if you were playing local files maybe it's a weird issue with that

**Comment by PriZmRL** [comment]
It works now! I've been playing downloaded offline songs, imported songs and streaming it

**Comment by PriZmRL** [comment]
Is it possible for you to grab album cover from the music playing and show it in the status as well?

**Comment by wxllow** [comment]
> It works now! I've been playing downloaded offline songs, imported songs and streaming it

Ah, it might have been some weird issue with the Music app of how they handle some local files. 


> Is it possible for you to grab album cover from the music playing and show it in the status as well?

Unfortunately no, I wish it was :( but the discord API doesn't allow dynamically uploading images

**Comment by wxllow** [comment]
**Also, if you could please star the repo that would be very greatly appreciated :)**

**Comment by wxllow** [comment]
> Done ^^ Another suggestion: I think the status should disappear if the paused song hasn't been played for X amount of time. I've been on my mac without listening to music for 2 hours and it still shows my last song as paused in discord.

That's a good idea, how long do you think it should be until it stops showing?!

**Comment by PriZmRL** [comment]
I think 10 to 30 minutes should be a good one. I’d personally make it 10 minutes

**Comment by wxllow** [comment]
> I think 10 to 30 minutes should be a good one. I’d personally make it 10 minutes

I finally got to it! <https://github.com/wxllow/applemusicrp/releases/tag/2.2.0>

**Comment by PriZmRL** [comment]
Nice! i'll give the mac version a test and let you know about it.

**Comment by PriZmRL** [comment]
Btw, it might be possible to actually show the album artwork. This person apparently has done it;

https://github.com/jackcrane/apple-music-presence

**Comment by PriZmRL** [comment]
Sadly the discord status is not disappearing after 10 minutes. Do you need logs?

**Comment by wxllow** [comment]
> Btw, it might be possible to actually show the album artwork. This person apparently has done it;
> 
> https://github.com/jackcrane/apple-music-presence

Oh wow, that actually works! I was able to get it to work with a test image, so maybe I will be able to get it to work, I'll look into it more today

**Comment by wxllow** [comment]
> Nice! i'll give the mac version a test and let you know about it.



> Sadly the discord status is not disappearing after 10 minutes. Do you need logs?

oops, I found the problem and I fixed it, I'll upload the patched build soon

**Comment by PriZmRL** [comment]
Nice! waiting for it

**Comment by wxllow** [comment]
@PriZmRL <https://github.com/wxllow/applemusicrp/releases/tag/2.2.1>

**Comment by wxllow** [comment]
@PriZmRL https://github.com/wxllow/applemusicrp/releases/tag/3.0.0 **ALBUM ARTWORK** :)))

**Comment by PriZmRL** [comment]
You are fast! trying out 3.0.0 right now. Will let you know if anything goes out of the way :P

**Comment by wxllow** [comment]
@PriZmRL tell me if it works!

**Comment by PriZmRL** [comment]
10 minute timeout works!
