### ISSUE TITLE
not launching

### ISSUE THREAD

**Issue by nikorue** [wxllow/applemusicrp#7]
<img width="264" alt="image" src="https://user-images.githubusercontent.com/67581183/164772346-056270f0-189b-4b12-b3a9-690c7e81f5ad.png">
<img width="232" alt="image" src="https://user-images.githubusercontent.com/67581183/164772432-9a2a1e0c-e8de-4db4-b9c8-f58e68cbfe11.png">
<img width="319" alt="image" src="https://user-images.githubusercontent.com/67581183/164772587-788267a0-ec08-43a4-b361-8d408f41f73a.png">

**Comment by wxllow** [comment]
Could you please give some more specifics? Like, did you have Discord open when you launched the app??

**Comment by nikorue** [comment]
Discord was launched before starting the app, I can try any of the 4 branches of discord if that fits the fancy, only 1 instance was launched at the time of the program launched, AM was open in bg

**Comment by wxllow** [comment]
> Discord was launched before starting the app, I can try any of the 4 branches of discord if that fits the fancy, only 1 instance was launched at the time of the program launched, AM was open in bg

try restarting discord and if that doesn't work try restarting your computer... sometimes discord rich presence has issues with apple silicon

**Comment by wxllow** [comment]
if that doesn't work, in terminal run:
`/Applications/applemusicrp.app/Contents/macOS/applemusicrp` and tell me what it outputs

**Comment by nikorue** [comment]
<img width="563" alt="image" src="https://user-images.githubusercontent.com/67581183/164877792-8fea3450-70d2-4462-a834-a79a5df38866.png">

**Comment by nikorue** [comment]
noticing a trend here and I believe it's a MacOS bug, it seems to be the problem that brings the Siri to halt, mic not working in a vm and other weird little things, it worked after a hard reboot

**Comment by wxllow** [comment]
Yeah, not much I can do about that :(
