### ISSUE TITLE
an option to change the hover over

### ISSUE THREAD

**Issue by nikorue** [wxllow/applemusicrp#8]
<img width="172" alt="image" src="https://user-images.githubusercontent.com/67581183/164892111-a2f611db-c159-4ecd-a4eb-03fdea4d5a66.png">
can we have the ability to change this to something else (at least to a rick roll =)

**Comment by wxllow** [comment]
sure!

**Comment by nikorue** [comment]
custom icon for the app?

**Comment by nikorue** [comment]
option to start with the device, or a plugin for BetterDiscord/Vizality/PowerCord

**Comment by nikorue** [comment]
any way of making it say "listening to" rather than "playing a game"

**Comment by wxllow** [comment]
> 

no thats not possible

**Comment by wxllow** [comment]
> any way of making it say "listening to" rather than "playing a game"

no that's not possible sorry

**Comment by wxllow** [comment]
> 



> option to start with the device, or a plugin for BetterDiscord/Vizality/PowerCord

Just got to System Preferences > Users & Groups > Select yourself > Login Items and then add applemusicrp

**Comment by wxllow** [comment]
> custom icon for the app?

wdym? a custom icon for the menu bar or what?

**Comment by wxllow** [comment]
<https://github.com/wxllow/applemusicrp/wiki/Customization> I'll be having a beta to do this later today or tomorrow
